/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GuitarImport } from './routes/guitar'
import { Route as DeliciousImport } from './routes/delicious'
import { Route as ClassImport } from './routes/class'
import { Route as IdImport } from './routes/$Id'
import { Route as IndexImport } from './routes/index'
import { Route as GuitarGuitarIdImport } from './routes/guitar_.$guitarId'
import { Route as DeliciousDeliciousIdImport } from './routes/delicious_.$deliciousId'
import { Route as ClassClassIdImport } from './routes/class_.$classId'

// Create/Update Routes

const GuitarRoute = GuitarImport.update({
  id: '/guitar',
  path: '/guitar',
  getParentRoute: () => rootRoute,
} as any)

const DeliciousRoute = DeliciousImport.update({
  id: '/delicious',
  path: '/delicious',
  getParentRoute: () => rootRoute,
} as any)

const ClassRoute = ClassImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => rootRoute,
} as any)

const IdRoute = IdImport.update({
  id: '/$Id',
  path: '/$Id',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GuitarGuitarIdRoute = GuitarGuitarIdImport.update({
  id: '/guitar_/$guitarId',
  path: '/guitar/$guitarId',
  getParentRoute: () => rootRoute,
} as any)

const DeliciousDeliciousIdRoute = DeliciousDeliciousIdImport.update({
  id: '/delicious_/$deliciousId',
  path: '/delicious/$deliciousId',
  getParentRoute: () => rootRoute,
} as any)

const ClassClassIdRoute = ClassClassIdImport.update({
  id: '/class_/$classId',
  path: '/class/$classId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$Id': {
      id: '/$Id'
      path: '/$Id'
      fullPath: '/$Id'
      preLoaderRoute: typeof IdImport
      parentRoute: typeof rootRoute
    }
    '/class': {
      id: '/class'
      path: '/class'
      fullPath: '/class'
      preLoaderRoute: typeof ClassImport
      parentRoute: typeof rootRoute
    }
    '/delicious': {
      id: '/delicious'
      path: '/delicious'
      fullPath: '/delicious'
      preLoaderRoute: typeof DeliciousImport
      parentRoute: typeof rootRoute
    }
    '/guitar': {
      id: '/guitar'
      path: '/guitar'
      fullPath: '/guitar'
      preLoaderRoute: typeof GuitarImport
      parentRoute: typeof rootRoute
    }
    '/class_/$classId': {
      id: '/class_/$classId'
      path: '/class/$classId'
      fullPath: '/class/$classId'
      preLoaderRoute: typeof ClassClassIdImport
      parentRoute: typeof rootRoute
    }
    '/delicious_/$deliciousId': {
      id: '/delicious_/$deliciousId'
      path: '/delicious/$deliciousId'
      fullPath: '/delicious/$deliciousId'
      preLoaderRoute: typeof DeliciousDeliciousIdImport
      parentRoute: typeof rootRoute
    }
    '/guitar_/$guitarId': {
      id: '/guitar_/$guitarId'
      path: '/guitar/$guitarId'
      fullPath: '/guitar/$guitarId'
      preLoaderRoute: typeof GuitarGuitarIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$Id': typeof IdRoute
  '/class': typeof ClassRoute
  '/delicious': typeof DeliciousRoute
  '/guitar': typeof GuitarRoute
  '/class/$classId': typeof ClassClassIdRoute
  '/delicious/$deliciousId': typeof DeliciousDeliciousIdRoute
  '/guitar/$guitarId': typeof GuitarGuitarIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$Id': typeof IdRoute
  '/class': typeof ClassRoute
  '/delicious': typeof DeliciousRoute
  '/guitar': typeof GuitarRoute
  '/class/$classId': typeof ClassClassIdRoute
  '/delicious/$deliciousId': typeof DeliciousDeliciousIdRoute
  '/guitar/$guitarId': typeof GuitarGuitarIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$Id': typeof IdRoute
  '/class': typeof ClassRoute
  '/delicious': typeof DeliciousRoute
  '/guitar': typeof GuitarRoute
  '/class_/$classId': typeof ClassClassIdRoute
  '/delicious_/$deliciousId': typeof DeliciousDeliciousIdRoute
  '/guitar_/$guitarId': typeof GuitarGuitarIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$Id'
    | '/class'
    | '/delicious'
    | '/guitar'
    | '/class/$classId'
    | '/delicious/$deliciousId'
    | '/guitar/$guitarId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$Id'
    | '/class'
    | '/delicious'
    | '/guitar'
    | '/class/$classId'
    | '/delicious/$deliciousId'
    | '/guitar/$guitarId'
  id:
    | '__root__'
    | '/'
    | '/$Id'
    | '/class'
    | '/delicious'
    | '/guitar'
    | '/class_/$classId'
    | '/delicious_/$deliciousId'
    | '/guitar_/$guitarId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  ClassRoute: typeof ClassRoute
  DeliciousRoute: typeof DeliciousRoute
  GuitarRoute: typeof GuitarRoute
  ClassClassIdRoute: typeof ClassClassIdRoute
  DeliciousDeliciousIdRoute: typeof DeliciousDeliciousIdRoute
  GuitarGuitarIdRoute: typeof GuitarGuitarIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  ClassRoute: ClassRoute,
  DeliciousRoute: DeliciousRoute,
  GuitarRoute: GuitarRoute,
  ClassClassIdRoute: ClassClassIdRoute,
  DeliciousDeliciousIdRoute: DeliciousDeliciousIdRoute,
  GuitarGuitarIdRoute: GuitarGuitarIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$Id",
        "/class",
        "/delicious",
        "/guitar",
        "/class_/$classId",
        "/delicious_/$deliciousId",
        "/guitar_/$guitarId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$Id": {
      "filePath": "$Id.tsx"
    },
    "/class": {
      "filePath": "class.tsx"
    },
    "/delicious": {
      "filePath": "delicious.tsx"
    },
    "/guitar": {
      "filePath": "guitar.tsx"
    },
    "/class_/$classId": {
      "filePath": "class_.$classId.tsx"
    },
    "/delicious_/$deliciousId": {
      "filePath": "delicious_.$deliciousId.tsx"
    },
    "/guitar_/$guitarId": {
      "filePath": "guitar_.$guitarId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
