/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Indexcopy2Import } from './routes/index copy 2'
import { Route as IndexcopyImport } from './routes/index copy'
import { Route as ListImport } from './routes/List'
import { Route as IndexImport } from './routes/index'
import { Route as List2Import } from './routes/List_.2'
import { Route as List1Import } from './routes/List_.1'

// Create/Update Routes

const Indexcopy2Route = Indexcopy2Import.update({
  id: '/index copy 2',
  path: '/index copy 2',
  getParentRoute: () => rootRoute,
} as any)

const IndexcopyRoute = IndexcopyImport.update({
  id: '/index copy',
  path: '/index copy',
  getParentRoute: () => rootRoute,
} as any)

const ListRoute = ListImport.update({
  id: '/List',
  path: '/List',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const List2Route = List2Import.update({
  id: '/List_/2',
  path: '/List/2',
  getParentRoute: () => rootRoute,
} as any)

const List1Route = List1Import.update({
  id: '/List_/1',
  path: '/List/1',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/List': {
      id: '/List'
      path: '/List'
      fullPath: '/List'
      preLoaderRoute: typeof ListImport
      parentRoute: typeof rootRoute
    }
    '/index copy': {
      id: '/index copy'
      path: '/index copy'
      fullPath: '/index copy'
      preLoaderRoute: typeof IndexcopyImport
      parentRoute: typeof rootRoute
    }
    '/index copy 2': {
      id: '/index copy 2'
      path: '/index copy 2'
      fullPath: '/index copy 2'
      preLoaderRoute: typeof Indexcopy2Import
      parentRoute: typeof rootRoute
    }
    '/List_/1': {
      id: '/List_/1'
      path: '/List/1'
      fullPath: '/List/1'
      preLoaderRoute: typeof List1Import
      parentRoute: typeof rootRoute
    }
    '/List_/2': {
      id: '/List_/2'
      path: '/List/2'
      fullPath: '/List/2'
      preLoaderRoute: typeof List2Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/List': typeof ListRoute
  '/index copy': typeof IndexcopyRoute
  '/index copy 2': typeof Indexcopy2Route
  '/List/1': typeof List1Route
  '/List/2': typeof List2Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/List': typeof ListRoute
  '/index copy': typeof IndexcopyRoute
  '/index copy 2': typeof Indexcopy2Route
  '/List/1': typeof List1Route
  '/List/2': typeof List2Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/List': typeof ListRoute
  '/index copy': typeof IndexcopyRoute
  '/index copy 2': typeof Indexcopy2Route
  '/List_/1': typeof List1Route
  '/List_/2': typeof List2Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/List'
    | '/index copy'
    | '/index copy 2'
    | '/List/1'
    | '/List/2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/List' | '/index copy' | '/index copy 2' | '/List/1' | '/List/2'
  id:
    | '__root__'
    | '/'
    | '/List'
    | '/index copy'
    | '/index copy 2'
    | '/List_/1'
    | '/List_/2'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListRoute: typeof ListRoute
  IndexcopyRoute: typeof IndexcopyRoute
  Indexcopy2Route: typeof Indexcopy2Route
  List1Route: typeof List1Route
  List2Route: typeof List2Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListRoute: ListRoute,
  IndexcopyRoute: IndexcopyRoute,
  Indexcopy2Route: Indexcopy2Route,
  List1Route: List1Route,
  List2Route: List2Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/List",
        "/index copy",
        "/index copy 2",
        "/List_/1",
        "/List_/2"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/List": {
      "filePath": "List.tsx"
    },
    "/index copy": {
      "filePath": "index copy.tsx"
    },
    "/index copy 2": {
      "filePath": "index copy 2.tsx"
    },
    "/List_/1": {
      "filePath": "List_.1.tsx"
    },
    "/List_/2": {
      "filePath": "List_.2.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
